version: '3.7'

services:
  web:
    container_name: web-prod
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    links:
      - db
  db:
    container_name: db-prod
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: xt
      MYSQL_PASSWORD: yolo
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  db_data: {}
